### ISSUE TITLE
not compatible to  Magento 2.4.0 

### ISSUE THREAD

**Issue by MartinKuhl** [Vendic/magento2-clean-cron-schedule#2]
Just updated to Magento 2.4.0 and now I cannot use this package anymore because of version clashes with magento/framework.

Please update: "require": {
FROM
        "magento/framework": "^100.0.0 || ^101.0.0 || ^102.0.0"
TO
        "magento/framework": "^100.0.0 || ^101.0.0 || ^102.0.0 || ^103.0.0"

**Comment by Tjitse-E** [comment]
@MartinKuhl  can you create a PR for this?

**Comment by MartinKuhl** [comment]
hi @Tjitse-E no I didn't I am not so deep into Github. I see this issue in other projects too and this was the resolution.

**Comment by MartinKuhl** [comment]
now I created a pull: https://github.com/Vendic/magento2-clean-cron-schedule/pull/3

**Comment by Tjitse-E** [comment]
Thanks!
